version: "3.3"
name: Funcaflix
networks:
  funcap-networks:
    driver: bridge
services:
  # app:
  #   build: .
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   entrypoint: ["/bin/sh", "-c", "yarn install && yarn dev"]
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3000
  #   volumes:
  #     - .:/home/node/app
  redis:
    image: redis
    ports:
      - "6379:6379"

  mariadb:
    image: mariadb
    restart: always
    networks:
      - funcap-networks
    volumes:
      - .docker/mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test