import { v4 as uuid } from 'uuid'

const items = [
	// this is the parent or 'item'
	{
		label: 'Ficção',
		value: uuid(),
		// these are the options or 'sub items'
		options: [
			{
				label: 'Ação e Aventura',
				value: uuid(),
			},
			{
				label: 'Ficção afro-americana',
				value: uuid(),
			},
			{
				label: 'Antologias',
				value: uuid(),
			},
			{
				label: 'Infantil',
				value: uuid(),
			},
			{
				label: 'Ficção Cristâ',
				value: uuid(),
			},
			{
				label: 'Clássicos',
				value: uuid(),
			},
			{ label: 'Quadrinhos e romances gráficos', value: uuid() },
			{ label: 'Chegando à maioridade', value: uuid() },
			{ label: 'Ficção Contemporânea', value: uuid() },
			{ label: 'Cultural e étnico', value: uuid() },
			{ label: 'Fantasia', value: uuid() },
			{ label: 'Fantasia épica', value: uuid() },
			{ label: 'Jogos e LitRPG', value: uuid() },
			{ label: 'Fantasia Urbana', value: uuid() },
			{ label: 'Ficção histórica', value: uuid() },
			{ label: 'Humor e comédia', value: uuid() },
			{ label: 'Ficção LGBTQIA+', value: uuid() },
			{ label: 'Ficção política', value: uuid() },
			{ label: 'Realismo mágico', value: uuid() },
			{ label: 'Mashups', value: uuid() },
			{ label: 'Mistério e crime', value: uuid() },
			{ label: 'Mistérios aconchegantes', value: uuid() },
			{ label: 'Mistérios Históricos', value: uuid() },
			{ label: 'Peças e roteiros', value: uuid() },
			{ label: 'Poesia', value: uuid() },
			{ label: 'Romance contemporâneo', value: uuid() },
			{ label: 'Romance histórico', value: uuid() },
			{ label: 'Romance Paranormal', value: uuid() },
			{ label: 'Comédia romântica', value: uuid() },
			{ label: 'Suspense Romântico', value: uuid() },
			{ label: 'Romance de viagem no tempo', value: uuid() },
			{ label: 'Ficção científica', value: uuid() },
			{ label: 'Distópico', value: uuid() },
			{ label: 'Ficção científica militar', value: uuid() },
			{ label: 'Pós-apocalíptico', value: uuid() },
			{ label: 'Space Opera', value: uuid() },
			{ label: 'Steampunk (e outros gêneros punk na ficção)', value: uuid() },
			{ label: 'Viagem no tempo', value: uuid() },
			{ label: 'Contos', value: uuid() },
			{ label: 'Temáticas e motivações', value: uuid() },
			{ label: 'Thriller e Suspense' },
			{ label: 'Espionagem', value: uuid() },
			{ label: 'Horror', value: uuid() },
			{ label: 'Thriller legal', value: uuid() },
			{ label: 'Thriller médico', value: uuid() },
			{ label: 'Thriller psicológico', value: uuid() },
			{ label: 'Techno-thriller', value: uuid() },
			{ label: 'Ficção Feminina', value: uuid() },
			{ label: 'Chick Lit', value: uuid() },
			{ label: 'Jovem adulto', value: uuid() },
			{ label: 'Novo Adulto', value: uuid() },
			{ label: 'Dramaturgia', value: uuid() },
			{ label: 'Questões Sociais e Familiares', value: uuid() },
			{ label: 'Fantasia para jovens adultos', value: uuid() },
		],
	},
	{
		label: 'Não Ficção',
		value: uuid(),
		options: [
			{
				label: 'Agricultura',
				value: uuid(),
			},
			{ label: 'Biografias e memórias', value: uuid() },
			{ label: 'Gestão de negócios', value: uuid() },
			{ label: 'Guias de carreira', value: uuid() },
			{ label: 'Não-ficção infantil', value: uuid() },
			{ label: 'Quadrinhos não ficção', value: uuid() },
			{ label: 'Computadores e Internet', value: uuid() },
			{
				label: 'Culinária, comida, vinho e bebidas espirituosas',
				value: uuid(),
			},
			{ label: 'Faça você mesmo e artesanato', value: uuid() },
			{ label: 'Projeto', value: uuid() },
			{ label: 'Educação e Referência', value: uuid() },
			{ label: 'Entretenimento', value: uuid() },
			{ label: 'Saúde e Bem-Estar', value: uuid() },
			{ label: 'Casa e jardim', value: uuid() },
			{ label: 'Humanidades e Ciências Sociais', value: uuid() },
			{ label: 'Arte', value: uuid() },
			{ label: 'História', value: uuid() },
			{ label: 'Lei', value: uuid() },
			{ label: 'Música', value: uuid() },
			{ label: 'Filosofia', value: uuid() },
			{ label: 'Ciência Política e Atualidades', value: uuid() },
			{ label: 'Psicologia', value: uuid() },
			{ label: 'Sociologia', value: uuid() },
			{ label: 'Inspirador', value: uuid() },
			{ label: 'LGBTQIA+ Não Ficção', value: uuid() },
			{ label: 'Matemática e Ciências', value: uuid() },
			{
				label: 'Ciências da Terra, do Espaço e do Meio Ambiente',
				value: uuid(),
			},
			{ label: 'Engenharia', value: uuid() },
			{ label: 'Contabilidade Finanças', value: uuid() },
			{ label: 'Medicina, enfermagem e odontologia', value: uuid() },
			{ label: 'Natureza', value: uuid() },
			{ label: 'Nova era', value: uuid() },
			{ label: 'Paternidade e famílias', value: uuid() },
			{ label: 'Fotografia', value: uuid() },
			{ label: 'Religião e Espiritualidade', value: uuid() },
			{ label: 'Ateísmo', value: uuid() },
			{ label: 'Não-ficção cristã', value: uuid() },
			{ label: 'Autoajuda e autoaprimoramento', value: uuid() },
			{ label: 'Sexo e Relacionamentos', value: uuid() },
			{ label: 'Esportes e atividades ao ar livre', value: uuid() },
			{ label: 'Tecnologia', value: uuid() },
			{ label: 'Viajar por', value: uuid() },
			{ label: 'Crime Verdadeiro', value: uuid() },
			{ label: 'Casamentos', value: uuid() },
			{ label: 'Escrita e Publicação', value: uuid() },
		],
	},
]

export default items
