name: CI - Next Build

on: [pull_request]

permissions: write-all

env:
  PATH_RELATIVE: ${{ secrets.PATH_RELATIVE }}

jobs:
  install:
    name: Installing Packages
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List Arquivos da Rota
        run: |
          cd $PATH_RELATIVE
          ls

  # next-build:
  #   name: Run Next Build
  #   needs: install
  #   runs-on: [self-hosted]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Restore node_modules
  #       uses: actions/cache@v2
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

  #     - name: Run Next Build
  #       run: yarn build
