name: Continuos Integration Pull Request V2

on: [pull_request]

permissions: write-all

jobs:
  install:
    name: Installing Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

  db-create:
    name: Docker Image Database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Cache Docker Images
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: foo-docker-cache-8350e5a3e24c153df2275c9f80692773-mariadb
          restore-keys: |
            foo-docker-cache-8350e5a3e24c153df2275c9f80692773-

      - name: Build Image
        run: cd .docker && docker compose up -d --build

  db-build:
    name: Create Maria DB
    runs-on: ubuntu-latest
    needs: [db-create, install]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Cache Docker Images
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: foo-docker-cache-8350e5a3e24c153df2275c9f80692773-mariadb
          restore-keys: |
            foo-docker-cache-8350e5a3e24c153df2275c9f80692773-

      - name: Cache Database MariaDB
        uses: actions/cache@v2
        with:
          path: .docker/mariadb-data
          key: ${{ runner.os }}-database-mapacultural-mariadb

      - name: Create Maria DB
        run: yarn build:database

  testing:
    name: Run Unit Test
    runs-on: ubuntu-latest
    needs: db-create
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Restore Database MariaDB
        uses: actions/cache@v2
        with:
          path: .docker/maria-db
          key: ${{ runner.os }}-database-mapacultural-mariadb

      - name: Run Unit Test
        run: yarn test:unitary
