name: Continuos Integration Pull Request V2

on: [pull_request]

jobs:
  install:
    name: Installing Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

  db-create:
    name: Docker Image Database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: foo-docker-cache-${{ github.workflow }}-mariadb
          restore-keys: |
            foo-docker-cache-${{ github.workflow }}-

      - name: Build Image
        run: cd .docker && docker compose up --build

  db-build:
    name: Create MariaDB
    needs: [db-create, install]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore Docker
        uses: actions/cache@v2
        with:
          key: foo-docker-cache-${{ github.workflow }}-mariadb
          restore-keys: |
            foo-docker-cache-${{ github.workflow }}-

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Create Maria DB
        run: yarn build:database

  testing:
    name: Run Unit Test
    runs-on: ubuntu-latest
    needs: db-build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Run Unit Test
        run: yarn test:unitary
