name: Continuos Integration Pull Request

on: [pull_request]

jobs:
  install:
    name: Installing Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

  db-create:
    name: Docker Image Database
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Build Image
        run: cd .docker && docker compose up -d

      - name: Create Maria DB
        run: yarn build:database

  testing:
    name: Run Unit Test
    runs-on: ubuntu-latest
    needs: db-create
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore DB
        uses: actions/cache@v2
        with:
          path: .docker/mariadb-data
          key: ${{ runner.os }}-database

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Run Unit Test
        run: yarn test:unitary
